name: Livesite CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: Linting and Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci
        
      - name: Add Mock Environment Variables
        run: echo "MONGODB_URI=mongodb://localhost:27017/testdb" >> .env.local

      - name: Run Linter
        run: npm run lint

      - name: Build Project
        run: npm run build